# Generated by Django 5.2.5 on 2025-08-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrepresentative',
            name='total_sales',
            field=models.IntegerField(default=0),
        ),
    ]
